// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/unser-elefant/remnawave-go/internal/api/model"
)

// NewMockdeviceAPI creates a new instance of MockdeviceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdeviceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdeviceAPI {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockdeviceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockdeviceAPI is an autogenerated mock type for the deviceAPI type
type MockdeviceAPI struct {
	mock.Mock
}

type MockdeviceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdeviceAPI) EXPECT() *MockdeviceAPI_Expecter {
	return &MockdeviceAPI_Expecter{mock: &_m.Mock}
}

// DeleteAll provides a mock function for the type MockdeviceAPI
func (_mock *MockdeviceAPI) DeleteAll(ctx context.Context, userID uint64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockdeviceAPI_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockdeviceAPI_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockdeviceAPI_Expecter) DeleteAll(ctx any, userID any) *MockdeviceAPI_DeleteAll_Call {
	return &MockdeviceAPI_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, userID)}
}

func (_c *MockdeviceAPI_DeleteAll_Call) Run(run func(ctx context.Context, userID uint64)) *MockdeviceAPI_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockdeviceAPI_DeleteAll_Call) Return(err error) *MockdeviceAPI_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockdeviceAPI_DeleteAll_Call) RunAndReturn(run func(ctx context.Context, userID uint64) error) *MockdeviceAPI_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockdeviceAPI
func (_mock *MockdeviceAPI) GetByUserID(ctx context.Context, userID uint64) (*model.DevicesResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.DevicesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*model.DevicesResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *model.DevicesResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DevicesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdeviceAPI_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockdeviceAPI_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockdeviceAPI_Expecter) GetByUserID(ctx any, userID any) *MockdeviceAPI_GetByUserID_Call {
	return &MockdeviceAPI_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockdeviceAPI_GetByUserID_Call) Run(run func(ctx context.Context, userID uint64)) *MockdeviceAPI_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockdeviceAPI_GetByUserID_Call) Return(devicesResponse *model.DevicesResponse, err error) *MockdeviceAPI_GetByUserID_Call {
	_c.Call.Return(devicesResponse, err)
	return _c
}

func (_c *MockdeviceAPI_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint64) (*model.DevicesResponse, error)) *MockdeviceAPI_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
