// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/unser-elefant/remnawave-go/internal/api/model"
)

// NewMockuserAPI creates a new instance of MockuserAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuserAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuserAPI {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockuserAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockuserAPI is an autogenerated mock type for the userAPI type
type MockuserAPI struct {
	mock.Mock
}

type MockuserAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockuserAPI) EXPECT() *MockuserAPI_Expecter {
	return &MockuserAPI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockuserAPI
func (_mock *MockuserAPI) Create(ctx context.Context, req *model.CreateUserRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateUserRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockuserAPI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockuserAPI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateUserRequest
func (_e *MockuserAPI_Expecter) Create(ctx any, req any) *MockuserAPI_Create_Call {
	return &MockuserAPI_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockuserAPI_Create_Call) Run(run func(ctx context.Context, req *model.CreateUserRequest)) *MockuserAPI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockuserAPI_Create_Call) Return(err error) *MockuserAPI_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockuserAPI_Create_Call) RunAndReturn(run func(ctx context.Context, req *model.CreateUserRequest) error) *MockuserAPI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetStream provides a mock function for the type MockuserAPI
func (_mock *MockuserAPI) GetStream(ctx context.Context, query model.UserStreamQuery) (*model.UsersResponse, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 *model.UsersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserStreamQuery) (*model.UsersResponse, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserStreamQuery) *model.UsersResponse); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UsersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserStreamQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockuserAPI_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type MockuserAPI_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - ctx context.Context
//   - query model.UserStreamQuery
func (_e *MockuserAPI_Expecter) GetStream(ctx any, query any) *MockuserAPI_GetStream_Call {
	return &MockuserAPI_GetStream_Call{Call: _e.mock.On("GetStream", ctx, query)}
}

func (_c *MockuserAPI_GetStream_Call) Run(run func(ctx context.Context, query model.UserStreamQuery)) *MockuserAPI_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserStreamQuery
		if args[1] != nil {
			arg1 = args[1].(model.UserStreamQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockuserAPI_GetStream_Call) Return(usersResponse *model.UsersResponse, err error) *MockuserAPI_GetStream_Call {
	_c.Call.Return(usersResponse, err)
	return _c
}

func (_c *MockuserAPI_GetStream_Call) RunAndReturn(run func(ctx context.Context, query model.UserStreamQuery) (*model.UsersResponse, error)) *MockuserAPI_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSubscription provides a mock function for the type MockuserAPI
func (_mock *MockuserAPI) RevokeSubscription(ctx context.Context, id uint64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockuserAPI_RevokeSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSubscription'
type MockuserAPI_RevokeSubscription_Call struct {
	*mock.Call
}

// RevokeSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockuserAPI_Expecter) RevokeSubscription(ctx any, id any) *MockuserAPI_RevokeSubscription_Call {
	return &MockuserAPI_RevokeSubscription_Call{Call: _e.mock.On("RevokeSubscription", ctx, id)}
}

func (_c *MockuserAPI_RevokeSubscription_Call) Run(run func(ctx context.Context, id uint64)) *MockuserAPI_RevokeSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockuserAPI_RevokeSubscription_Call) Return(err error) *MockuserAPI_RevokeSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockuserAPI_RevokeSubscription_Call) RunAndReturn(run func(ctx context.Context, id uint64) error) *MockuserAPI_RevokeSubscription_Call {
	_c.Call.Return(run)
	return _c
}
